"""make list foreign key not nullable

Revision ID: 629d645754ad
Revises: 6e659d538356
Create Date: 2020-05-17 16:53:39.215148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629d645754ad'
down_revision = '6e659d538356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'todolist',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'todolist',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
